import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { openSans } from "@/fonts/fonts";
import { cn } from "@/lib/utils";

export const metadata = {
  title: "Cyberhub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("w-screen min-h-screen", openSans.className)}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
