import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { openSans } from "@/fonts/fonts";

export const metadata = {
  title: "Cyberhub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
